version: '3.8'

services:
  web-app:
    build: .
    container_name: aplikasi_uas_html
    restart: always
    ports:
      - "8080:80"

  monitoring:
    image: louislam/uptime-kuma:1
    container_name: uptime_kuma_uas
    restart: always
    ports:
      - "3001:3001"
    volumes:
      - uptime-kuma-data:/app/data

volumes:
  uptime-kuma-data: